batch_size = 8
query_budget = 200000000
epoch_itrs = 20
g_iter = 1
d_iter = 5
lr_S = 1e-4 # old - 1e-2
lr_G = 1e-5 # old - 1e-4
nz = 100  # or 2000 depending on the query generator
log_interval = 10
loss = 'l1'
scheduler = 'multistep'
steps= [0.1, 0.3, 0.5]
scale = 3e-1
dataset = 'cifar10'
data_root = './data/'
model = 'resnet34_8x'
weight_decay = 5e-4
momentum = 0.9
no_cuda = False
seed = 1
ckpt = 'checkpoint/teacher/cifar10-resnet34_8x.pt'
student_load_path = None
model_id = "debug"
device = 0
log_dir = 'results'
approx_grad = 1
grad_m = 1
grad_epsilon = 1e-3
forward_differences = 1
no_logits = 1
logit_correction = 'mean'
rec_grad_norm = 1
MAZE = 0
store_checkpoints = 1
student_model = 'swinT'
cuda_device = "0"